// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yfaqgwzavulccnhisxxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmYXFnd3phdnVsY2NuaGlzeHhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMjA5MTksImV4cCI6MjA1NjU5NjkxOX0.xq-XsUWWIEmDTDcnGo-qXyKqp37Vl_suAFH656A-GYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);